name = "Dimension Abomination"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb90d277f0c5d7ee823353c5e61ef9f5b02cf0ed9a743f34922316c911f8a9e3"

[versions]
fabric = "0.15.3"
minecraft = "1.20.2"
